version: '3.4'
services:
  gateway-starter-api:
    build:
      context: ./
      target: builder
    image: gateway-starter-api
    command: yarn run dev
    volumes:
      - ./src:/home/app/src
      - ./package.json:/home/app/package.json
      - ./nodemon.json:/home/app/nodemon.json
    #      - ../commons-lib/dist:/home/app/node_modules/commons-lib/dist
    ports:
      - 8080:8080 # app port
      - 9101:9101 # metrics port
      - 10010:10010 # debug port
    networks:
      - backend
    environment:
      DEBUG: n9-node-conf # usefull to debug conf loading

networks:
  backend:
    external: true
